## Indexing

In [1]:
import numpy as np

In [2]:
list =[9,8,7,6];
var = np.array(list)

print(type(list))
print(type(var))
print(var.ndim)


<class 'list'>
<class 'numpy.ndarray'>
1


In [6]:
var1 = np.array([[9,8,7], [4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [11]:
 
var3d = np.array([[[1,2,3],[4,5,6]]])
print(var3d)
print(var3d.ndim)


[[[1 2 3]
  [4 5 6]]]
3


## Slicing Numpy Array ([start:end:step])

In [12]:
var = np.array([1,2,3,4,5])
print(var)

[1 2 3 4 5]


In [14]:
print('2 to 5= ', var[1:4])

2 to 5=  [2 3 4]


In [20]:
print(var[0:4:2])

[1 3]


In [21]:
print(var[2:])

[3 4 5]


In [22]:
print(var[:4])

[1 2 3 4]


In [23]:
print(var[::])

[1 2 3 4 5]


In [24]:
print(var[::2])

[1 3 5]


## Iteration on numpy

In [25]:
for i in var:
    print(i)

1
2
3
4
5
